removed error
UseInterstellar/Interstellar pull request #727
Opened 2024-05-29 21:32 UTC by natleef

there was a popup saying taming.io would crash interstellar, but it has been fixed according to this guy:
![image](https://github.com/UseInterstellar/Interstellar/assets/132697706/30df0a41-8d36-484a-a1a9-4fe9fa6584ba)

2024-05-29 22:45 UTC, IncognitoTGT commented
not true, interstellar hasn't updated it's uv version in ages,.,.

2024-05-30 05:27 UTC, IncognitoTGT commented
It's not a UV fix but it seems to work now

2024-05-30 05:27 UTC, IncognitoTGT requested changes
Can you also fix g.min.json?

2024-05-30 14:24 UTC, WatchGamingVideos commented
> ~not true, interstellar hasn't updated it's uv version in ages,.,.~
> 
> not a uv fix but next time dont jump to conclusions

Wait why not? Isn't always better to be on the latest (and most likely most secure) version? Is it broken?

Idk I'm a bit of a newer developer like in general so 

I'm also sorry if this is considered "yapping" I understand it can be annoying

2024-05-30 14:28 UTC, WatchGamingVideos approved these changes
I did it in g.min.json

2024-05-30 14:58 UTC, IncognitoTGT approved these changes

2024-05-30 14:58 UTC, merged